### ISSUE TITLE
📚 Add screenshots or animations to documentation

### ISSUE THREAD

**Issue by bdsoha** [kloudkit/ws-meta#12]
## Description

Generate screenshots or animations to enhance the readability and clarity of the documentation.

- Ensure that all assets have a maximum width of `740px`.
- Ensure that the default theme is set.
- Minimize the open tabs, files, and elements found in the image to focus on your goal.

### Tasks

- [x] kloudkit/workspace#237
- [ ] Add screenshots or animations to `tools/ssh.md`
- [x] Add screenshots or animations to `tools/docker.md`
- [x] kloudkit/workspace#238
- [ ] Add screenshots or animations to `tools/ws-cli.md`
- [x] Add screenshots or animations to `tools/kind.md`
- [x] Add screenshots or animations to `tools/ansible.md`
- [x] Add screenshots or animations to `tools/index.md`
- [ ] Add screenshots or animations to `editor/port-forwarding.md`
- [x] kloudkit/workspace#239
- [x] kloudkit/workspace#236
- [ ] Add screenshots or animations to `editor/aliases.md`
- [x] Add screenshots or animations to `editor/theme-and-fonts.md`
- [ ] Add screenshots or animations to `editor/features.md`
- [x] kloudkit/ws-meta#11
- [x] kloudkit/workspace#242
- [ ] Add screenshots or animations to `pages/getting-started.md`
- [x] Add screenshots or animations to `pages/extendable-configuration.md`
- [x] Add screenshots or animations to `pages/index.md`
- [x] Add screenshots or animations to `settings/secrets.md`
- [ ] Add screenshots or animations to `settings/autoload-scripts.md`
- [x] Add screenshots or animations to `settings/environment-variables.md`
- [x] Add screenshots or animations to `settings/enterprise-ca.md`
